// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ugaudxftmoiaroxxzzst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnYXVkeGZ0bW9pYXJveHh6enN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDEwNDQsImV4cCI6MjA3MjYxNzA0NH0.3b2qPNVmHKiq8ckgY5NVxC1c-Iaz9qO0RdpkU_WH94s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});